# Use the official Microsoft SQL Server 2019 image from the Docker Hub
FROM mcr.microsoft.com/mssql/server:2019-latest

# Set environment variables for the SQL Server instance
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=sqlserverPass10

# Expose the SQL Server port
EXPOSE 1433

# Start the SQL Server instance
CMD /opt/mssql/bin/sqlservr
